name: Flask CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black isort flake8

      - name: Format code with black
        run: black . --line-length 120

      - name: Sort imports with isort
        run: isort . --check-only

      - name: Lint with flake8
        run: flake8 . --max-line-length=120
